os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: C:\gopath\src\github.com\palletone\go-palletone
version: "{branch}.{build}"
environment:
  global:
    GOPATH: C:\gopath
    CC: gcc.exe
    GETH_ARCH: amd64
    MSYS2_ARCH: x86_64
    MSYS2_BITS: 64
    MSYSTEM: MINGW64
    PATH: C:\gopath\bin\;C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
  matrix:
    - GOVERSION: 1.12.9
      GO111MODULE: on


install:
  - git submodule update --init
  - rmdir C:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-%GETH_ARCH%.zip
  - 7z x go%GOVERSION%.windows-%GETH_ARCH%.zip -y -oC:\ > NUL
  - go version
  - gcc --version

  
build_script:
  - go build -mod=vendor .\cmd\gptn\

# after_build:
#   - go run build\ci.go archive -type zip -signer WINDOWS_SIGNING_KEY -upload ""
#   - go run build\ci.go nsis -signer WINDOWS_SIGNING_KEY -upload ""

test_script:
   - set CGO_ENABLED=1
   - go test -mod=vendor ./...
